### ISSUE TITLE
[GC-73] ASF unable to write wma lossless file

### ISSUE THREAD

**Issue by svollbehr** [vollbehr/php-reader#71]
> Original Google Code issue: [73](https://code.google.com/archive/p/php-reader/issues/73)
> Status: New
> Labels: Type-Defect, Priority-Medium
> Google Code user ID: -5486003658497276815 | Reported on: 2013-03-03T18:17:38+00:00

Encoder Windows Media Audio 9.1 Lossless
Encoder Settings VBR Quality 100, 44 kHz, 2 channel 16 bit 1-pass VBR
Audio Quality Perfect (Lossless)
Type Media Center file    [.wma]

Able to read the file fine, but "Example #3: How to write ASF information" fails with:

PHP Fatal error:  Uncaught exception 'Zend_Media_Asf_Exception' with message 'Operation not supported' in C:\progs\phpinclude\php-reader-1.8.1\library\Zend\Media\Asf\Object\IndexParameters.php:123
Stack trace:
#0 C:\progs\phpinclude\php-reader-1.8.1\library\Zend\Media\Asf\Object\HeaderExtension.php(96): Zend_Media_Asf_Object_IndexParameters->write(Object(Zend_Io_StringWriter))
#1 C:\progs\phpinclude\php-reader-1.8.1\library\Zend\Media\Asf\Object\Header.php(117): Zend_Media_Asf_Object_HeaderExtension->write(Object(Zend_Io_StringWriter))
#2 C:\progs\phpinclude\php-reader-1.8.1\library\Zend\Media\Asf.php(170): Zend_Media_Asf_Object_Header->write(Object(Zend_Io_StringWriter))
#3 C:\progs\RDA\silence\test.php(19): Zend_Media_Asf->write(NULL)
#4 {main}
  thrown in C:\progs\phpinclude\php-reader-1.8.1\library\Zend\Media\Asf\Object\IndexParameters.php on line 123

Looking at IndexParameters.php:123 reveals that the exception is by design. What to do?

**Comment by svollbehr** [comment]
Fixed in 1.9
